### ISSUE TITLE
Indirect modification of overloaded element of Outl1ne\PageManager\Models\Region has no effect 

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [outl1ne/nova-page-manager#141]
Im using Nova Page Manager 5.8.2, when I edit a Region and hit save, I keep seeing an error that I cannot make any sense of

```
Indirect modification of overloaded element of Outl1ne\PageManager\Models\Region has no effect {"userId":1,"exception":"[object] (ErrorException(code: 0): Indirect modification of overloaded element of Outl1ne\\PageManager\\Models\\Region has no effect at /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Collections/helpers.php:124)
[stacktrace]
#0 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(259): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Indirect modifi...', '/Users/matt/Dev...', 124)
#1 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(124): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(8, 'Indirect modifi...', '/Users/matt/Dev...', 124)
#2 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/Fields/Field.php(480): data_set(Object(Outl1ne\\PageManager\\Models\\Region), Object(Illuminate\\Support\\Stringable), 'Your Shortlist')
#3 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/Fields/Field.php(463): Laravel\\Nova\\Fields\\Field->fillAttributeFromRequest(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest), 'data->en->headi...', Object(Outl1ne\\PageManager\\Models\\Region), 'data->en->headi...')
#4 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/Fields/Field.php(445): Laravel\\Nova\\Fields\\Field->fillAttribute(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest), 'data->en->headi...', Object(Outl1ne\\PageManager\\Models\\Region), 'data->en->headi...')
#5 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/Fields/Field.php(419): Laravel\\Nova\\Fields\\Field->fillInto(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest), Object(Outl1ne\\PageManager\\Models\\Region), 'data->en->headi...')
#6 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Laravel\\Nova\\Fields\\Field->fill(Object(Laravel\\Nova\\Http\\Requests\\NovaRequest), Object(Outl1ne\\PageManager\\Models\\Region))
#7 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Laravel\\Nova\\Fields\\Text), 0)
#8 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map(Object(Closure), Array, Array)
#9 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(719): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#10 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->map(Object(Closure))
#11 /Users/matt/Dev/Sites/hottest100/vendor/outl1ne/nova-page-manager/src/Nova/Fields/PageManagerField.php(102): Illuminate\\Support\\HigherOrderCollectionProxy->__call('fill', Array)
#12 /Users/matt/Dev/Sites/hottest100/vendor/outl1ne/nova-page-manager/src/Nova/Fields/PageManagerField.php(48): Outl1ne\\PageManager\\Nova\\Fields\\PageManagerField->fillFields(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest), 'data', Object(Laravel\\Nova\\Fields\\FieldCollection), Object(Outl1ne\\PageManager\\Models\\Region))
#13 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Outl1ne\\PageManager\\Nova\\Fields\\PageManagerField->fill(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest), Object(Outl1ne\\PageManager\\Models\\Region))
#14 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(Outl1ne\\PageManager\\Nova\\Fields\\PageManagerField), 2)
#15 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map(Object(Closure), Array, Array)
#16 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(719): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#17 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->map(Object(Closure))
#18 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/FillsFields.php(100): Illuminate\\Support\\HigherOrderCollectionProxy->__call('fill', Array)
#19 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/FillsFields.php(43): Laravel\\Nova\\Resource::fillFields(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest), Object(Outl1ne\\PageManager\\Models\\Region), Object(Laravel\\Nova\\Fields\\FieldCollection))
#20 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/Http/Controllers/ResourceUpdateController.php(46): Laravel\\Nova\\Resource::fillForUpdate(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest), Object(Outl1ne\\PageManager\\Models\\Region))
#21 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(30): Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController->Laravel\\Nova\\Http\\Controllers\\{closure}(Object(Illuminate\\Database\\MySqlConnection))
#22 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/Http/Controllers/ResourceUpdateController.php(64): Illuminate\\Database\\Connection->transaction(Object(Closure))
#23 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController->__invoke(Object(Laravel\\Nova\\Http\\Requests\\UpdateResourceRequest), 'regions', '1')
#24 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('__invoke', Array)
#25 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Nova\\Http\\Controllers\\ResourceUpdateController), '__invoke')
#26 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#27 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\\Routing\\Route->run()
#28 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/Http/Middleware/Authorize.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\Authorize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /Users/matt/Dev/Sites/hottest100/vendor/whitecube/nova-flexible-content/src/Http/Middleware/InterceptFlexibleAttributes.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Whitecube\\NovaFlexibleContent\\Http\\Middleware\\InterceptFlexibleAttributes->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#33 /Users/matt/Dev/Sites/hottest100/app/Http/Middleware/SecureHeaders.php(10): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/Http/Middleware/BootTools.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\BootTools->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/Http/Middleware/DispatchServingNovaEvent.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\DispatchServingNovaEvent->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/matt/Dev/Sites/hottest100/vendor/inertiajs/inertia-laravel/src/Middleware.php(92): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Inertia\\Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/Http/Middleware/Authenticate.php(31): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'admin')
#45 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#52 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/matt/Dev/Sites/hottest100/app/Http/Middleware/CheckIp.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\CheckIp->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Routing/Router.php(728): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#61 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#62 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#63 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#64 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#65 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/matt/Dev/Sites/hottest100/vendor/laravel/nova/src/Http/Middleware/ServeNova.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Nova\\Http\\Middleware\\ServeNova->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /Users/matt/Dev/Sites/hottest100/app/Http/Middleware/ShareImageCookie.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\ShareImageCookie->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /Users/matt/Dev/Sites/hottest100/app/Http/Middleware/SecureHeaders.php(10): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\SecureHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#72 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#79 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#88 /Users/matt/Dev/Sites/hottest100/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#89 /Users/matt/Dev/Sites/hottest100/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#90 /Users/matt/.composer/vendor/laravel/valet/server.php(234): require('/Users/matt/Dev...')
#91 {main}
"} 
```

**Comment by matthewjumpsoffbuildings** [comment]
I discovered that rolling back to version 5.7.3 resolves the issue. Something has been broken in version 5.8.x

**Comment by KasparRosin** [comment]
This is a bug inside nova 
https://github.com/laravel/nova-issues/issues/5005

As per this comment, the fix is yet to be released.
https://github.com/laravel/nova-issues/issues/5042#issuecomment-1311277945

**Comment by matthewjumpsoffbuildings** [comment]
I see, is there a reason that Nova Page Manager 5.7.3 is not affected while 5.8.2 is? Since I am not changing my nova version?

**Comment by matthewjumpsoffbuildings** [comment]
I have since updated to Nova 4.19.0 which resolves this issue
