### ISSUE TITLE
Rolling back error

### ISSUE THREAD

**Issue by iveliniliev90** [outl1ne/nova-page-manager#69]
Hello, after php artisan migrate:refresh  I get this error:

Rolling back: 2019_11_29_000005_make_slug_locale_published_parent_id_pair_unique
 
Illuminate\Database\QueryException 

 SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'nova_page_manager_locale_slug_published_unique' (SQL: alter table `nova_page_manager_pages` add unique `nov
a_page_manager_locale_slug_published_unique`(`locale`, `slug`, `published`))

stacktrace 
```
[2021-01-11 13:30:11] local.ERROR: SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'nova_page_manager_locale_slug_published_unique' (SQL: alter table `nova_page_manager_pages` add unique `nova_page_manager_locale_slug_published_unique`(`locale`, `slug`, `published`)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'nova_page_manager_locale_slug_published_unique' (SQL: alter table `nova_page_manager_pages` add unique `nova_page_manager_locale_slug_published_unique`(`locale`, `slug`, `published`)) at C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:678)
[stacktrace]
#0 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(638): Illuminate\\Database\\Connection->runQueryCallback('alter table `no...', Array, Object(Closure))
#1 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(472): Illuminate\\Database\\Connection->run('alter table `no...', Array, Object(Closure))
#2 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Blueprint.php(102): Illuminate\\Database\\Connection->statement('alter table `no...')
#3 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Builder.php(337): Illuminate\\Database\\Schema\\Blueprint->build(Object(Illuminate\\Database\\MySqlConnection), Object(Illuminate\\Database\\Schema\\Grammars\\MySqlGrammar))
#4 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Builder.php(184): Illuminate\\Database\\Schema\\Builder->build(Object(Illuminate\\Database\\Schema\\Blueprint))
#5 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(261): Illuminate\\Database\\Schema\\Builder->table('nova_page_manag...', Object(Closure))
#6 C:\\laragon\\www\\atparts\\vendor\\optimistdigital\
ova-page-manager\\database\\migrations\\2019_11_29_000005_make_slug_locale_published_parent_id_pair_unique.php(46): Illuminate\\Support\\Facades\\Facade::__callStatic('table', Array)
#7 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(392): MakeSlugLocalePublishedParentidPairUnique->down()
#8 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(401): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}()
#9 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(363): Illuminate\\Database\\Migrations\\Migrator->runMigration(Object(MakeSlugLocalePublishedParentidPairUnique), 'down')
#10 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(284): Illuminate\\Database\\Migrations\\Migrator->runDown('C:\\\\laragon\\\\www\\\\...', Object(stdClass), false)
#11 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(334): Illuminate\\Database\\Migrations\\Migrator->rollbackMigrations(Array, Array, Array)
#12 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(313): Illuminate\\Database\\Migrations\\Migrator->resetMigrations(Array, Array, false)
#13 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Console\\Migrations\\ResetCommand.php(67): Illuminate\\Database\\Migrations\\Migrator->reset(Array, false)
#14 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php(541): Illuminate\\Database\\Console\\Migrations\\ResetCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#15 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Console\\Migrations\\ResetCommand.php(69): Illuminate\\Database\\Migrations\\Migrator->usingConnection(NULL, Object(Closure))
#16 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\ResetCommand->handle()
#17 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#19 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#20 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#21 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call(Array)
#22 C:\\laragon\\www\\atparts\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#23 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#24 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\CallsCommands.php(68): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#25 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Concerns\\CallsCommands.php(28): Illuminate\\Console\\Command->runCommand('migrate:reset', Array, Object(Illuminate\\Console\\OutputStyle))
#26 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Console\\Migrations\\RefreshCommand.php(110): Illuminate\\Console\\Command->call('migrate:reset', Array)
#27 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Console\\Migrations\\RefreshCommand.php(55): Illuminate\\Database\\Console\\Migrations\\RefreshCommand->runReset(NULL, Array)
#28 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\RefreshCommand->handle()
#29 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#30 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#31 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#32 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(610): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#33 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(136): Illuminate\\Container\\Container->call(Array)
#34 C:\\laragon\\www\\atparts\\vendor\\symfony\\console\\Command\\Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#35 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#36 C:\\laragon\\www\\atparts\\vendor\\symfony\\console\\Application.php(971): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#37 C:\\laragon\\www\\atparts\\vendor\\symfony\\console\\Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\RefreshCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#38 C:\\laragon\\www\\atparts\\vendor\\symfony\\console\\Application.php(166): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#39 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#40 C:\\laragon\\www\\atparts\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 C:\\laragon\\www\\atparts\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#42 {main}
```

**Comment by Tarpsvo** [comment]
Hi! This should be fixed in version 3.3.0. Thanks for reporting this and good luck!
